### ISSUE TITLE
Compatibility with iRedMail 1.3.1

### ISSUE THREAD

**Issue by mikekgr** [jeekkd/iRedMail-scripts#2]
Dear @jeekkd 
do you know if your very helpful scripts are compatible and running well in the recent iRedMail 1.3.1 ?  Especially I interesting in for MariaDB and Ubuntu server 20.04
Thanks!

**Comment by jeekkd** [comment]
Hello, thanks for asking. I am updating the repo shortly, based off the last two release notes the scripts currently are compatible with iRedMail 1.3.1 so I will update the README to reflect that. However as for MariaDB I have not tested it at all, only for Postgres. So if you decide to use any scripts with MariaDB please proceed with caution. Soon MariaDB support will come as it would be optimal to officially support both

**Comment by jeekkd** [comment]
Repo update complete.

i'll open a new issue about MariaDB testing, feel free to post there if you do any testing

**Comment by mikekgr** [comment]
Dear @jeekkd 
thanks for updating you repo. I am here if you need a tester regarding MariaDB.
