### ISSUE TITLE
Problem on Debian

### ISSUE THREAD

**Issue by 0xAF** [jeekkd/iRedMail-scripts#6]
Hi.
The scripts are using #!/bin/sh to run.
On Debian 10 the /bin/sh is linked to /bin/dash. This is a problem, because lines like this:
``` if [ "$1" == "-h" ] || [ "$1" == "--h" ] || [ "$1" == "/h" ] || [ $# -gt 0 ]; then ```
would not work on Dash.
Here is the error:
> ./list-active-accounts.sh: 24: [: unexpected operator

Could you please change #!/bin/sh to #!/bin/bash, so the scripts will work as expected?
Thanks.

**Comment by jeekkd** [comment]
Hello, I fixed this with commit 5f05452. I replaced the sh shebang with bash.
